---
title: "Statistical Inference"
output: html_notebook
---
# Introduction

Null hypothesis (H~o~): The claim that is not interesting
Alternative Hypothesis (H~A~) : The claim cooresponding to the research hypothesis

**The "goal" is to disprove the null hypothesis**

# Randomized Distributions

The idea behind this is to explore the variation of distribution under the circumstances in which the null hypothesis is true.

# Foundations of Inference

It is possible to use `table()` to create a contigency table of a dataframe

```{r table() example}
library(tidyverse)

sex <- rep(c("male", "female"), 50)
promote <- rep(c("promoted", "not promoted"), 50)

promotions <- data.frame(sex = sample(sex, 50, replace = TRUE),
                         promote = sample(promote, 50, replace = TRUE))
glimpse(promotions) 

table(promotions)

promotions %>%
group_by(sex) %>%
summarise(promoted_prop = mean(promote == "promoted"))

```


# p-value

> probability of observing data as or more extreme than what we actually got given that the null hypothesis is true



# Hypothesis Testing

Error Types

Type 1 Error: Rejecting theH~o~ in favor of H~A~ when in fact the H~o~ is **TRUE**  
* This type of error is also known as a **False Positive**

Type 2 Error: Not rejecting the H~o~ when in fact the H~A~ is **TRUE**  
* This is called **FALSE Negative Rate** and is what we typically want to avoid in most cases.

# Parameters & Confidence Intervals

Hypothesis Test: Under which diet plan will participants lose more weight on average?  

Confidence Interval: How much should participants expect to lose on average?  

A **parameter** is a numerical value from the population.  

A confidence interval is a range of numbers that (hopefully) captures the true parameter.  

## Bootstrapping

p^ : *statistic*, proprotion of successes in sample

p : parameter*, proportion of successes in population


We are 95% confident that the true proportion lies within the range of the confidence interval
bootstrapping repeatedly samples from the original sample.  
* sample with replacement

*Standard Error* describes how the statistic varies around parameter.  
* variability of the sample proportion. 

Approximately 95% of samples will produce p^'s within 2SE of the center.





